apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::197372856450:role/my-eks-cluster-node
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - userarn: arn:aws:iam::197372856450:user/me
      username: me
      groups:
      - eks-console-dashboard-full-access-group
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system